{{ if .Capabilities.APIVersions.Has "logging.banzaicloud.io/v1beta1" }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ include "server.fullname" . }}
spec:
  loki:
    url: http://loki.loki.svc:3100
    configure_kubernetes_labels: true
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{ include "server.fullname" . }}
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: none
  match:
    - select:
        labels:
        {{- include "server.selectorLabels" .| nindent 10 }}
  localOutputRefs:
    - {{ include "server.fullname" . }}
{{ end }}